import { supabase } from './supabase.js';
import { requireBackoffice, setupShell, money, esc } from './auth.js';
const $=id=>document.getElementById(id);
let ctx=null,mode='daily',periodKey='',manual={},signals={};
const autoKeys=new Set(['D01','D05','D08','D10']);
const daily=[
 {group:'ก่อนเปิดร้าน',key:'D01',title:'เปิดกะ (Open Shift)',detail:'ระบบตรวจอัตโนมัติ เมื่อมีกะของ Business Date นี้จะเปลี่ยนเป็น Complete',auto:true,action:'เปิดกะจาก POS'},
 {group:'ก่อนเปิดร้าน',key:'D02',title:'ตรวจ Stock ก่อนเปิด',detail:'เช็กวัตถุดิบหลัก ของใกล้หมด/หมด และยอดพร้อมขาย',href:'./stock/ingredients.html',label:'เปิด Stock'},
 {group:'ก่อนเปิดร้าน',key:'D03',title:'ตรวจ PO / Receive',detail:'รับของที่เข้าวันนี้ให้ครบ และตรวจ PO ที่ยังค้าง',href:'./purchasing/purchase-orders.html',label:'เปิด PO / รับของ'},
 {group:'ก่อนเปิดร้าน',key:'D04',title:'Production / Prep พร้อมขาย',detail:'ทำ Prep ที่จำเป็น เช่น หมูแดง หมูกรอบ น้ำซุป เกี๊ยว ข้าว',href:'./stock/production.html',label:'เปิด Production'},
 {group:'ก่อนเปิดร้าน',key:'D05',title:'พร้อมเปิดขาย',detail:'ปลดล็อกอัตโนมัติเมื่อขั้นตอนก่อนเปิดร้านครบ',auto:true},
 {group:'ระหว่างวัน',key:'D06',title:'ตรวจงานขาย / Order ค้าง',detail:'ตรวจโต๊ะ, Kitchen, QR Order และรายการผิดปกติก่อนปิดร้าน',href:'./finance/sales-history.html',label:'ตรวจยอดขาย'},
 {group:'ก่อนปิดวัน',key:'D07',title:'ตรวจค่าใช้จ่ายวันนี้',detail:'บันทึกและตรวจ Expense ของวันนี้ให้ครบ',href:'./finance/expenses.html',label:'เปิด Expense'},
 {group:'ก่อนปิดวัน',key:'D08',title:'นับเงินและ Close Shift',detail:'ระบบตรวจอัตโนมัติจาก Daily Closing ว่าทุกกะปิดและนับเงินครบแล้ว',auto:true,href:'./finance/daily-closing.html',label:'Daily Closing'},
 {group:'ก่อนปิดวัน',key:'D09',title:'ตรวจ Daily Closing',detail:'ตรวจ Sales, Cash/QR, COGS, Profit, Cash Difference และ KPI ก่อน EOD',href:'./finance/daily-closing.html',label:'ตรวจรายงาน'},
 {group:'ก่อนปิดวัน',key:'D10',title:'End of Day',detail:'ขั้นตอนสุดท้าย ระบบจะ Complete เมื่อ Business Date เดินไปวันถัดไป',auto:true,href:'./finance/end-of-day.html',label:'ไป End of Day'}
];
const monthly=[
 {group:'เตรียมปิดเดือน',key:'M01',title:'ตรวจ EOD ทุกวันในเดือน',detail:'ยืนยันว่าไม่มีวันขายค้างปิด',href:'./finance/end-of-day.html',label:'เปิด EOD'},
 {group:'เตรียมปิดเดือน',key:'M02',title:'ตรวจ PO / Receive / AP',detail:'PO, ใบรับสินค้า และเจ้าหนี้ต้องบันทึกครบ',href:'./finance/accounts-payable.html',label:'ตรวจ AP'},
 {group:'Stock เดือน',key:'M03',title:'Full Stock Count',detail:'นับ Raw / Prep / Packaging / Beverage ให้ครบ',href:'./stock/count.html',label:'Stock Count'},
 {group:'Stock เดือน',key:'M04',title:'ปิดรอบ Stock',detail:'ปิด Stock Closing หลัง Full Count เพื่อได้ Actual COGS',href:'./stock/closing.html',label:'Stock Closing'},
 {group:'การเงินเดือน',key:'M05',title:'ตรวจ Expenses ครบเดือน',detail:'ค่าเช่า ค่าแรง ไฟ น้ำ แก๊ส Delivery และค่าใช้จ่ายอื่น',href:'./finance/expenses.html',label:'Expenses'},
 {group:'การเงินเดือน',key:'M06',title:'ตรวจ P&L เดือน',detail:'Revenue, COGS, Food Cost, Gross Profit และ Operating Profit',href:'./finance/pnl.html',label:'P&L'},
 {group:'การเงินเดือน',key:'M07',title:'ตรวจ Cash Flow / Reconciliation',detail:'เงินเข้า เงินออก QR/Cash และยอดกระทบธนาคาร',href:'./finance/cash-flow.html',label:'Cash Flow'},
 {group:'ปิดเดือน',key:'M08',title:'รับรองปิดเดือน',detail:'เดือนนี้ตรวจครบแล้ว พร้อมเริ่มเดือนใหม่'}
];
const yearly=[
 {group:'เตรียมปิดปี',key:'Y01',title:'ตรวจ Month-End ครบ 12 เดือน',detail:'ทุกเดือนต้องผ่านการปิดและตรวจรายงาน'},
 {group:'เตรียมปิดปี',key:'Y02',title:'ตรวจ PO / AP / Supplier ค้าง',detail:'ตรวจเอกสารซื้อและหนี้ Supplier ปลายปี',href:'./finance/accounts-payable.html',label:'Accounts Payable'},
 {group:'Stock ปี',key:'Y03',title:'Full Stock Count สิ้นปี',detail:'นับ Stock 100% หลังปิดการขายวันสุดท้าย',href:'./stock/count.html',label:'Stock Count'},
 {group:'Stock ปี',key:'Y04',title:'Stock Closing สิ้นปี',detail:'ปิดรอบ Stock เพื่อยืนยัน Ending Inventory',href:'./stock/closing.html',label:'Stock Closing'},
 {group:'สรุปปี',key:'Y05',title:'ตรวจ Expenses ทั้งปี',detail:'ตรวจรายการค่าใช้จ่ายและรายการยกเลิก',href:'./finance/expenses.html',label:'Expenses'},
 {group:'สรุปปี',key:'Y06',title:'ตรวจ P&L ทั้งปี',detail:'ตรวจยอดขาย ต้นทุน กำไร และ Margin ทั้งปี',href:'./finance/pnl.html',label:'P&L'},
 {group:'สรุปปี',key:'Y07',title:'ตรวจ Cash Flow ทั้งปี',detail:'ตรวจเงินสด QR Supplier Payment และ Net Cash Flow',href:'./finance/cash-flow.html',label:'Cash Flow'},
 {group:'สรุปปี',key:'Y08',title:'Export / Backup รายงานสำคัญ',detail:'เก็บ Sales, Purchase, Expense, Stock, P&L, Cash Flow สำหรับ Audit'},
 {group:'ปิดปี',key:'Y09',title:'รับรองปิดปี',detail:'ตรวจครบทั้งหมด พร้อมเริ่มปีธุรกิจใหม่'}
];
function localDate(d=new Date()){let x=new Date(d),y=x.getFullYear(),m=String(x.getMonth()+1).padStart(2,'0'),dd=String(x.getDate()).padStart(2,'0');return `${y}-${m}-${dd}`}
function dt(v){return v?new Intl.DateTimeFormat('th-TH',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'-'}
function rows(){return mode==='daily'?daily:mode==='month'?monthly:yearly}
function periodType(){return mode==='daily'?'daily':mode==='month'?'month':'year'}
function isManualDone(k){return !!manual[k]}
function isDone(k){if(mode!=='daily')return isManualDone(k);if(k==='D01')return !!signals.shiftOpened;if(k==='D05')return ['D01','D02','D03','D04'].every(isDone);if(k==='D08')return !!signals.closingComplete;if(k==='D10')return !!signals.eodComplete;return isManualDone(k)}
function firstIncomplete(){return rows().find(x=>!isDone(x.key))?.key||null}
function unlocked(index){if(index===0)return true;return rows().slice(0,index).every(x=>isDone(x.key))}
function signalDetail(k){if(mode!=='daily')return '';if(k==='D01')return signals.shiftOpened?`มีกะแล้ว • ${signals.shiftCount||1} กะ`: 'ยังไม่พบกะของวันนี้';if(k==='D03'&&signals.openPoCount!=null)return ` • PO เปิดอยู่ ${signals.openPoCount} รายการ`;if(k==='D04'&&signals.productionCount!=null)return ` • Production วันนี้ ${signals.productionCount} Batch`;if(k==='D08')return signals.closingComplete?'ทุกกะปิดและนับเงินครบแล้ว':`ปิดกะ ${signals.closedShiftCount||0}/${signals.shiftCount||0} • นับเงิน ${signals.countedShiftCount||0}/${signals.shiftCount||0}`;if(k==='D10')return signals.eodComplete?'Business Date ปิดแล้ว':'รอ End of Day';return ''}
async function loadManual(){const {data,error}=await supabase.rpc('backoffice_operations_list_v1',{p_period_type:periodType(),p_period_key:periodKey});if(error)throw error;manual={};(data||[]).forEach(x=>manual[x.task_key]=x)}
async function mark(key){let idx=rows().findIndex(x=>x.key===key);if(!unlocked(idx))return alert('กรุณาทำขั้นตอนก่อนหน้าให้ Complete ก่อน');const {error}=await supabase.rpc('backoffice_operations_mark_v1',{p_period_type:periodType(),p_period_key:periodKey,p_task_key:key,p_note:null});if(error)return alert(error.message);await refresh()}
async function unmark(key){if(!confirm('ยกเลิกสถานะ Complete ของขั้นตอนนี้?'))return;const {error}=await supabase.rpc('backoffice_operations_unmark_v1',{p_period_type:periodType(),p_period_key:periodKey,p_task_key:key});if(error)return alert(error.message);await refresh()}
async function currentBusinessDate(){const {data,error}=await supabase.rpc('backoffice_current_business_date_v22');if(error)throw error;const p=Array.isArray(data)?data[0]:data;return p?.business_date||localDate()}
async function loadDailySignals(){signals={};const selected=periodKey;try{const {data}=await supabase.rpc('get_current_shift');const sh=Array.isArray(data)?data[0]:data;if(sh?.id)signals.currentShift=sh}catch{}
 try{const {data}=await supabase.rpc('backoffice_daily_closing_v1',{p_date:selected});const s=data||{},c=s.cash||{};signals.shiftCount=Number(c.shift_count||0);signals.closedShiftCount=Number(c.closed_shift_count||0);signals.countedShiftCount=Number(c.counted_shift_count||0);signals.shiftOpened=signals.shiftCount>0||!!signals.currentShift;signals.closingComplete=!!c.closing_complete}catch{signals.shiftOpened=!!signals.currentShift;signals.closingComplete=false}
 try{const {data}=await supabase.rpc('backoffice_list_purchase_orders');signals.openPoCount=(data||[]).filter(x=>['draft','ordered','partial'].includes(x.status)).length}catch{}
 try{const from=`${selected}T00:00:00+07:00`,to=`${selected}T23:59:59+07:00`;const {data}=await supabase.rpc('backoffice_list_production_batches',{p_from:from,p_to:to});signals.productionCount=(data||[]).length}catch{}
 try{const bd=await currentBusinessDate();signals.currentBusinessDate=bd;signals.eodComplete=bd>selected}catch{signals.eodComplete=false}}
function renderSummary(){let list=rows(),done=list.filter(x=>isDone(x.key)).length,pct=Math.round(done/list.length*100);$('progressText').textContent=`${done}/${list.length} Complete`;$('progressPct').textContent=`${pct}%`;$('progressBar').style.width=`${pct}%`;let cards=[];if(mode==='daily')cards=[['Business Date',periodKey],['กะวันนี้',signals.shiftCount??'-'],['PO เปิดอยู่',signals.openPoCount??'-'],['Production วันนี้',signals.productionCount??'-']];else cards=[['รอบ',periodKey],['Complete',done],['คงเหลือ',list.length-done],['สถานะ',done===list.length?'พร้อมปิด':'กำลังดำเนินการ']];$('summaryCards').innerHTML=cards.map(x=>`<div class="ops-kpi"><small>${esc(x[0])}</small><strong>${esc(x[1])}</strong></div>`).join('');$('completeBanner').classList.toggle('ops-hidden',done!==list.length);$('completeBanner').textContent=mode==='daily'?'✅ งานประจำวันครบทุกขั้นตอนแล้ว':mode==='month'?'✅ Month-End Checklist ครบแล้ว พร้อมเริ่มเดือนใหม่':'✅ Year-End Checklist ครบแล้ว พร้อมเริ่มปีใหม่'}
function render(){renderSummary();let first=firstIncomplete(),html='',lastGroup='';rows().forEach((x,i)=>{if(x.group!==lastGroup){if(lastGroup)html+='</div></section>';html+=`<section class="ops-section"><div class="ops-section-title"><h3>${esc(x.group)}</h3></div><div class="ops-list">`;lastGroup=x.group}let done=isDone(x.key),lock=!unlocked(i),manualDone=isManualDone(x.key),cls=done?'complete':lock?'locked':x.key===first?'current':'',status=done?'✓ Complete':lock?'🔒 Locked':'● Pending',detail=x.detail+signalDetail(x.key);let actions='';if(x.href)actions+=`<a class="ops-btn" ${lock?'aria-disabled="true" tabindex="-1"':'href="'+x.href+'"'}>${esc(x.label||'เปิด')}</a>`;if(!x.auto&&!done)actions+=`<button class="ops-btn primary" data-mark="${x.key}" ${lock?'disabled':''}>✓ ยืนยันเสร็จแล้ว</button>`;if(!x.auto&&done)actions+=`<button class="ops-btn done" disabled>✓ Complete</button><button class="ops-btn" data-unmark="${x.key}">แก้ไข</button>`;if(x.auto&&!done&&!x.href)actions+=`<button class="ops-btn" disabled>รอระบบตรวจ</button>`;let stamp=manualDone?` • ${esc(manual[x.key].completed_by_name||'-')} ${dt(manual[x.key].completed_at)}`:'';html+=`<article class="ops-step ${cls}"><div class="ops-step-no">${done?'✓':i+1}</div><div><div class="ops-step-title">${esc(x.title)} <span class="ops-status">${status}</span></div><div class="ops-step-detail">${esc(detail)}${stamp}</div></div><div class="ops-actions">${actions}</div></article>`});if(lastGroup)html+='</div></section>';$('workflow').innerHTML=html;document.querySelectorAll('[data-mark]').forEach(b=>b.onclick=()=>mark(b.dataset.mark));document.querySelectorAll('[data-unmark]').forEach(b=>b.onclick=()=>unmark(b.dataset.unmark));let done=rows().filter(x=>isDone(x.key)).length;$('message').className='ops-message '+(done===rows().length?'ok':'warn');$('message').textContent=done===rows().length?'งานรอบนี้ครบแล้ว':`ขั้นตอนถัดไป: ${rows().find(x=>x.key===first)?.title||'-'} • กรุณาทำตามลำดับเพื่อไม่ให้ข้ามงานสำคัญ`}
function setupPeriodControls(){let now=new Date();if(mode==='daily'){periodKey=periodKey&&/^\d{4}-\d{2}-\d{2}$/.test(periodKey)?periodKey:localDate();$('periodControls').innerHTML=`<label>Business Date <input id="periodInput" type="date" value="${periodKey}"></label>`}else if(mode==='month'){periodKey=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;$('periodControls').innerHTML=`<label>เดือน <input id="periodInput" type="month" value="${periodKey}"></label>`}else{periodKey=String(now.getFullYear());$('periodControls').innerHTML=`<label>ปี <input id="periodInput" type="number" min="2020" max="2100" value="${periodKey}"></label>`}$('periodInput').onchange=async e=>{periodKey=e.target.value;await refresh()}}
async function refresh(){try{$('message').className='ops-message';$('message').textContent='กำลังตรวจสอบสถานะ...';await loadManual();if(mode==='daily')await loadDailySignals();render()}catch(e){console.error(e);$('message').className='ops-message warn';$('message').textContent='โหลด Workflow ไม่สำเร็จ: '+(e?.message||'Unknown error')}}
document.querySelectorAll('.ops-tab').forEach(b=>b.onclick=async()=>{document.querySelectorAll('.ops-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode;$('opsTitle').textContent=mode==='daily'?'ลำดับงานประจำวัน':mode==='month'?'Month-End Closing':'Year-End Closing';$('opsSubtitle').textContent=mode==='daily'?'ทำตามขั้นตอนจากบนลงล่าง ระบบจะเปลี่ยนเป็นสีเขียวเมื่อ Complete':mode==='month'?'เช็กลิสต์ก่อนปิดเดือนและเริ่มเดือนใหม่':'เช็กลิสต์ก่อนปิดปีและเริ่มปีใหม่';setupPeriodControls();await refresh()});$('refreshBtn').onclick=refresh;
ctx=await requireBackoffice();if(ctx){setupShell(ctx,'operations');try{periodKey=await currentBusinessDate()}catch{periodKey=localDate()}setupPeriodControls();await refresh()}
