(function(){
'use strict';
const path=location.pathname.replace(/\\/g,'/');
const here=path.split('/').pop()||'';
const inFinance=path.includes('/finance/');
const inStock=path.includes('/stock/');
const inPurchasing=path.includes('/purchasing/');
const depth=(inFinance||inStock||inPurchasing)?'../':'./';
const links={dashboard:depth+'dashboard.html',finance:depth+'finance/financial-summary.html',stock:depth+'stock/ingredients.html',purchasing:depth+'purchasing/purchase-orders.html',daily:depth+'finance/daily-closing.html',eod:depth+'finance/end-of-day.html',sales:depth+'finance/sales-history.html',recon:depth+'finance/reconciliation.html',pnl:depth+'finance/pnl.html',expenses:depth+'finance/expenses.html',readiness:depth+'finance/cost-quality.html',costFix:depth+'finance/cost-fix.html',count:depth+'stock/count.html',movements:depth+'stock/movements.html',waste:depth+'stock/waste-loss.html',recipes:depth+'stock/recipes.html',production:depth+'stock/production.html',reports:depth+'stock/reports.html',cost:depth+'stock/cost-control.html',suppliers:depth+'purchasing/suppliers.html',docs:depth+'purchasing/purchase-documents.html',returns:depth+'purchasing/purchase-returns.html',employees:depth+'employees.html'};
function activeKey(){if(here==='dashboard.html')return'dashboard';if(inFinance)return'finance';if(inStock)return'stock';if(inPurchasing)return'purchasing';return'more'}
function item(key,href,icon,label){const el=document.createElement(href?'a':'button');if(href)el.href=href;else el.type='button';el.className='jk24-bottom-item'+(activeKey()===key?' active':'');el.dataset.key=key;el.setAttribute('aria-label',label);if(activeKey()===key)el.setAttribute('aria-current','page');el.innerHTML=`<span class="jk24-bottom-icon" aria-hidden="true">${icon}</span><span class="jk24-bottom-label">${label}</span>`;return el}
function buildMore(){const backdrop=document.createElement('div');backdrop.className='jk24-more-backdrop no-print';const sheet=document.createElement('section');sheet.className='jk24-more-sheet no-print';sheet.setAttribute('aria-hidden','true');sheet.setAttribute('aria-label','เมนูเพิ่มเติม');sheet.innerHTML=`<div class="jk24-sheet-head"><strong>เมนูเพิ่มเติม</strong><button class="jk24-sheet-close" type="button" aria-label="ปิดเมนู">×</button></div><div class="jk24-sheet-section">งานประจำวัน</div><div class="jk24-sheet-grid"><a class="jk24-sheet-link" href="${links.daily}">🌙 Daily Closing</a><a class="jk24-sheet-link" href="${links.eod}">🔐 End of Day</a><a class="jk24-sheet-link" href="${links.sales}">🧾 ประวัติยอดขาย</a><a class="jk24-sheet-link" href="${links.recon}">💳 กระทบยอด</a></div><div class="jk24-sheet-section">การเงิน</div><div class="jk24-sheet-grid"><a class="jk24-sheet-link" href="${links.pnl}">📈 P&amp;L</a><a class="jk24-sheet-link" href="${links.expenses}">🧾 ค่าใช้จ่าย</a><a class="jk24-sheet-link" href="${links.readiness}">✅ Cost Quality</a><a class="jk24-sheet-link" href="${links.costFix}">🛠️ Cost Fix</a></div><div class="jk24-sheet-section">Stock &amp; Cost</div><div class="jk24-sheet-grid"><a class="jk24-sheet-link" href="${links.count}">🧮 Stock Count</a><a class="jk24-sheet-link" href="${links.movements}">🔄 Stock Movement</a><a class="jk24-sheet-link" href="${links.waste}">🗑️ Waste / Loss</a><a class="jk24-sheet-link" href="${links.recipes}">🍳 Recipe / BOM</a><a class="jk24-sheet-link" href="${links.production}">🏭 Production</a><a class="jk24-sheet-link" href="${links.reports}">📊 Stock Report</a><a class="jk24-sheet-link" href="${links.cost}">💰 Cost Control</a></div><div class="jk24-sheet-section">จัดซื้อ / ระบบ</div><div class="jk24-sheet-grid"><a class="jk24-sheet-link" href="${links.suppliers}">🚚 Supplier</a><a class="jk24-sheet-link" href="${links.docs}">🧾 Purchase Documents</a><a class="jk24-sheet-link" href="${links.returns}">↩️ Purchase Returns</a><a class="jk24-sheet-link" href="${links.employees}">👥 พนักงาน</a></div>`;document.body.append(backdrop,sheet);const close=()=>{backdrop.classList.remove('open');sheet.classList.remove('open');sheet.setAttribute('aria-hidden','true');document.documentElement.style.overflow=''};const open=()=>{backdrop.classList.add('open');sheet.classList.add('open');sheet.setAttribute('aria-hidden','false');document.documentElement.style.overflow='hidden'};backdrop.addEventListener('click',close);sheet.querySelector('.jk24-sheet-close').addEventListener('click',close);document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});return{open,close}}
function init(){if(!document.querySelector('.topbar'))return;if(document.querySelector('.jk24-bottom-nav'))return;document.body.classList.add('jk24-has-bottom-nav');const more=buildMore();const nav=document.createElement('nav');nav.className='jk24-bottom-nav no-print';nav.setAttribute('aria-label','เมนูหลัก');nav.append(item('dashboard',links.dashboard,'⌂','หน้าหลัก'),item('finance',links.finance,'฿','การเงิน'),item('stock',links.stock,'▦','Stock'),item('purchasing',links.purchasing,'🛒','จัดซื้อ'),item('more',null,'•••','เพิ่มเติม'));nav.querySelector('[data-key="more"]').addEventListener('click',more.open);document.body.appendChild(nav)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
