(function(){
'use strict';
const path=location.pathname.replace(/\\/g,'/');
const here=path.split('/').pop()||'';
const inFinance=path.includes('/finance/');
const inStock=path.includes('/stock/');
const inPurchasing=path.includes('/purchasing/');
const depth=(inFinance||inStock||inPurchasing)?'../':'./';
const links={dashboard:depth+'dashboard.html',finance:depth+'finance/financial-summary.html',stock:depth+'stock/ingredients.html',purchasing:depth+'purchasing/purchase-orders.html',daily:depth+'finance/daily-closing.html',eod:depth+'finance/end-of-day.html',sales:depth+'finance/sales-history.html',recon:depth+'finance/reconciliation.html',pnl:depth+'finance/pnl.html',expenses:depth+'finance/expenses.html',readiness:depth+'finance/cost-quality.html',costFix:depth+'finance/cost-fix.html',count:depth+'stock/count.html',movements:depth+'stock/movements.html',waste:depth+'stock/waste-loss.html',recipes:depth+'stock/recipes.html',production:depth+'stock/production.html',reports:depth+'stock/reports.html',cost:depth+'stock/cost-control.html',suppliers:depth+'purchasing/suppliers.html',docs:depth+'purchasing/purchase-documents.html',returns:depth+'purchasing/purchase-returns.html',employees:depth+'employees.html'};
function activeKey(){if(here==='dashboard.html')return'dashboard';if(inFinance)return'finance';if(inStock)return'stock';if(inPurchasing)return'purchasing';return'more'}
function icon(name){
  const common='viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"';
  const icons={
    home:`<svg ${common}><path d="M3.5 10.6 12 3.8l8.5 6.8"/><path d="M5.6 9.2V20h12.8V9.2"/><path d="M9.5 20v-6h5v6"/></svg>`,
    finance:`<svg ${common}><rect x="3" y="5.5" width="18" height="13" rx="3"/><path d="M15.5 9h5.5v6h-5.5a3 3 0 0 1 0-6Z"/><path d="M7 9.2h4"/></svg>`,
    stock:`<svg ${common}><path d="M4 7.5 12 3l8 4.5-8 4.5-8-4.5Z"/><path d="M4 12.5 12 17l8-4.5"/><path d="M4 17 12 21l8-4"/><path d="M12 12v9"/></svg>`,
    cart:`<svg ${common}><path d="M3 4h2l1.8 9.1a2 2 0 0 0 2 1.6h7.7a2 2 0 0 0 1.9-1.4L20 7H6"/><circle cx="9" cy="19" r="1.4"/><circle cx="17" cy="19" r="1.4"/></svg>`,
    more:`<svg ${common}><circle cx="5" cy="12" r="1.35" fill="currentColor" stroke="none"/><circle cx="12" cy="12" r="1.35" fill="currentColor" stroke="none"/><circle cx="19" cy="12" r="1.35" fill="currentColor" stroke="none"/></svg>`
  };
  return icons[name]||icons.more;
}
function item(key,href,iconName,label){const el=document.createElement(href?'a':'button');if(href)el.href=href;else el.type='button';el.className='jk25-bottom-item'+(activeKey()===key?' active':'');el.dataset.key=key;el.setAttribute('aria-label',label);if(activeKey()===key)el.setAttribute('aria-current','page');el.innerHTML=`<span class="jk25-bottom-icon">${icon(iconName)}</span><span class="jk25-bottom-label">${label}</span>`;return el}
function buildMore(){const backdrop=document.createElement('div');backdrop.className='jk25-more-backdrop no-print';const sheet=document.createElement('section');sheet.className='jk25-more-sheet no-print';sheet.setAttribute('aria-hidden','true');sheet.setAttribute('aria-label','เมนูเพิ่มเติม');sheet.innerHTML=`<div class="jk25-sheet-head"><strong>เมนูเพิ่มเติม</strong><button class="jk25-sheet-close" type="button" aria-label="ปิดเมนู">×</button></div><div class="jk25-sheet-section">งานประจำวัน</div><div class="jk25-sheet-grid"><a class="jk25-sheet-link" href="${links.daily}">🌙 Daily Closing</a><a class="jk25-sheet-link" href="${links.eod}">🔐 End of Day</a><a class="jk25-sheet-link" href="${links.sales}">🧾 ประวัติยอดขาย</a><a class="jk25-sheet-link" href="${links.recon}">💳 กระทบยอด</a></div><div class="jk25-sheet-section">การเงิน</div><div class="jk25-sheet-grid"><a class="jk25-sheet-link" href="${links.pnl}">📈 P&amp;L</a><a class="jk25-sheet-link" href="${links.expenses}">🧾 ค่าใช้จ่าย</a><a class="jk25-sheet-link" href="${links.readiness}">✅ Cost Quality</a><a class="jk25-sheet-link" href="${links.costFix}">🛠️ Cost Fix</a></div><div class="jk25-sheet-section">Stock &amp; Cost</div><div class="jk25-sheet-grid"><a class="jk25-sheet-link" href="${links.count}">🧮 Stock Count</a><a class="jk25-sheet-link" href="${links.movements}">🔄 Stock Movement</a><a class="jk25-sheet-link" href="${links.waste}">🗑️ Waste / Loss</a><a class="jk25-sheet-link" href="${links.recipes}">🍳 Recipe / BOM</a><a class="jk25-sheet-link" href="${links.production}">🏭 Production</a><a class="jk25-sheet-link" href="${links.reports}">📊 Stock Report</a><a class="jk25-sheet-link" href="${links.cost}">💰 Cost Control</a></div><div class="jk25-sheet-section">จัดซื้อ / ระบบ</div><div class="jk25-sheet-grid"><a class="jk25-sheet-link" href="${links.suppliers}">🚚 Supplier</a><a class="jk25-sheet-link" href="${links.docs}">🧾 Purchase Documents</a><a class="jk25-sheet-link" href="${links.returns}">↩️ Purchase Returns</a><a class="jk25-sheet-link" href="${links.employees}">👥 พนักงาน</a></div>`;document.body.append(backdrop,sheet);const close=()=>{backdrop.classList.remove('open');sheet.classList.remove('open');sheet.setAttribute('aria-hidden','true');document.documentElement.style.overflow=''};const open=()=>{backdrop.classList.add('open');sheet.classList.add('open');sheet.setAttribute('aria-hidden','false');document.documentElement.style.overflow='hidden'};backdrop.addEventListener('click',close);sheet.querySelector('.jk25-sheet-close').addEventListener('click',close);document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});return{open,close}}
function init(){if(!document.querySelector('.topbar'))return;if(document.querySelector('.jk25-bottom-nav'))return;document.body.classList.add('jk25-has-bottom-nav');const more=buildMore();const nav=document.createElement('nav');nav.className='jk25-bottom-nav no-print';nav.setAttribute('aria-label','เมนูหลัก');nav.append(item('dashboard',links.dashboard,'home','หน้าหลัก'),item('finance',links.finance,'finance','การเงิน'),item('stock',links.stock,'stock','Stock'),item('purchasing',links.purchasing,'cart','จัดซื้อ'),item('more',null,'more','เพิ่มเติม'));nav.querySelector('[data-key="more"]').addEventListener('click',more.open);document.body.appendChild(nav)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
